# Generated by Django 5.2.8 on 2025-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pagina_alter_contato_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(max_length=350, verbose_name='Descrição')),
                ('destaque', models.CharField(default='Destaque', max_length=40, verbose_name='Etiqueta')),
                ('texto_precos', models.CharField(help_text="Ex.: R$ 2.999 ou 'frete grátis Brasil'", max_length=60, verbose_name='Texto de preço/benefício')),
                ('imagem', models.ImageField(upload_to='hero/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides do Carrossel',
                'ordering': ('ordem', '-atualizado_em'),
            },
        ),
    ]
