# Generated by Django 5.2.8 on 2025-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=350, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='destaque',
            field=models.CharField(blank=True, default='Destaque', max_length=40, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='texto_precos',
            field=models.CharField(blank=True, default='', help_text="Ex.: R$ 2.999 ou 'frete grátis Brasil'", max_length=60, null=True, verbose_name='Texto de preço/benefício'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Título'),
        ),
    ]
