# Generated by Django 5.2.8 on 2025-11-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carouselimage'),
        ('app', '0008_alter_heroslide_descricao_alter_heroslide_destaque_and_more'),
    ]

    operations = [
    ]
