# Generated by Django 5.2.8 on 2025-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20251130_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Use este campo para imagens hospedadas externamente (Cloudinary, Imgur, etc.)', max_length=500, null=True, verbose_name='URL Externa (Cloudinary/Imgur)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='desenvolvedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
